# @format

on:
  push:
  schedule:
    - cron: '0 7 * * *'

jobs:
  test_one_issues:
    env:
      VAR: print env
    runs-on: ubuntu-latest
    name: send weather to email
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get weather report
        run: |
          bash ./weather.sh
          env
