# @format

on:
  push:
  schedule:
    - cron: '0 7 * * *'

jobs:
  test_one_issues:
    runs-on: ubuntu-latest
    name: send weather to email
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get weather report
        run: bash ./weather.sh
      - name: send mail
        uses: dawidd6/action-send-mail@v3
        with:
          # Required mail server address:
          server_address: smtp.gmail.com
          # Required mail server port:
          server_port: 465
          # Optional (recommended): mail server username:
          username: ${{secrets.MAIL_USERNAME}}
          # Optional (recommended) mail server password:
          password: ${{secrets.MAIL_PASSWORD}}
          # Required mail subject:
          subject: send weather mail
          # Required recipients' addresses:
          to: fwqaaq@gmail.com,WENHUADAI@gmail.com
          # Required sender full name (address can be skipped):
          from: Jack # <user@example.com>
          # Optional whether this connection use TLS (default is true if server_port is 465)
          secure: true
          # Optional plain body:
          body: Build job of ${{github.repository}} completed successfully!
          # Optional HTML body read from file:
          html_body: file://result.html
