on: [push]

jobs:
  compatibility_deno:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.32.5
      - name: Run tests
        run: |
          deno --version
          deno run index.js
